name: Deploy Docusaurus
on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      base-href:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Compress Artifact
        run: tar -czf artifact.tar.gz -C build .

      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Move Artifact to Server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: artifact.tar.gz
          target: ~/websites/.temp/${{ inputs.host }}

      - name: SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            APP_DIR="$HOME/websites/${{ inputs.host }}"
            ARTIFACT="$HOME/websites/.temp/${{ inputs.host }}/artifact.tar.gz"

            mkdir -p "$APP_DIR"
            rm -rf "$APP_DIR"/*

            tar -xzf "$ARTIFACT" -C "$APP_DIR"

            cd "$APP_DIR"

            rm -rf /var/www/${{ inputs.host }}/html${{ inputs.base-href }}
            mkdir -p /var/www/${{ inputs.host }}/html${{ inputs.base-href }}
            mv ./* /var/www/${{ inputs.host }}/html${{ inputs.base-href }}

            rm -f "$ARTIFACT"
