name: Deploy Node.js
on:
  workflow_call:
    inputs:
      process-name:
        required: true
        type: string
    secrets:
      ENV_FILE:
        required: false

jobs:
  deploy-nodejs:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Fill Out the .env File
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Delete Previous Process Silently
        continue-on-error: true
        run: pm2 delete "${{ inputs.process-name }}"

      - name: Start a New Process
        run: pm2 start npm --name "${{ inputs.process-name }}" -- run preview

      - name: Save Current Process List
        run: pm2 save
